### ISSUE TITLE
PP-10[front] Welcome component (Main page) [1/3]

### ISSUE THREAD

**Issue by vandrela** [vandrela/portfolio#22]
As a user, I want to see the very first Welcome component on the Main page:

Acceptance criteria: We need to build a responsive react component with all matched styles, take a look at:
https://www.figma.com/file/UhuexeZHRxqoedo9RdQZZc/Folio-Website?type=design&node-id=116-1629&mode=dev

Other notations: ---

**Comment by vandrela** [comment]
.

**Comment by Shubh8899** [comment]
I would like to work on this

**Comment by vandrela** [comment]
Do You have any React/Typescript, TailwindCss exp? @Shubh8899

**Comment by Shubh8899** [comment]
Yes

**Comment by vandrela** [comment]
Feel free to start then :)
Let me know if You need any kind of additional info in the ticket description or something.
